Kadanza DAM media connector v0.0.1
chili-publish/studio-connector-framework pull request #81
Opened 2024-11-14 10:46 UTC by ivaylo-kostov-kad

* Add a connector with query, detail, filtering, metadata capabilities
* Add support only for oAuth2ResourceOwnerPassword auth at this stage

2024-11-20 11:17 UTC, ivaylo-kostov-kad commented
> @ivaylo-kostov-kad Would you be able to provide `readme.md` file with more or less similar information like in this PR example https://github.com/chili-publish/studio-connector-framework/pull/77/files#diff-d32e0ff4f8005cea104987800088b6ff736939d05f600c875db0b8f6f4501468 ? Of course if you see a potential to add more info, feel free to do it

@psamusev - done. Kept it simple at this stage and we'll update it later once more auth and other options are added.

2024-11-21 06:52 UTC, psamusev commented on src/connectors/kadanza/package.json
> +  "author": {
Since you're going to maintain the connector, please specify your information here

2024-11-21 08:25 UTC, ivaylo-kostov-kad commented on src/connectors/kadanza/package.json
> +  "author": {
Changed author to Kadanza

2024-11-21 08:25 UTC, ivaylo-kostov-kad commented on src/connectors/kadanza/package.json
> +    "@chili-publish/connector-cli": "^1"
Done

2024-11-21 08:25 UTC, ivaylo-kostov-kad commented on src/connectors/kadanza/package.json
> +    "@chili-publish/studio-connectors": "^1"
Done

2024-11-21 09:42 UTC, psamusev commented on src/connectors/kadanza/readme.md
> +  "name": "oAuth2AuthorizationCode",
we don't need specify `name` anymore, you can skip it from example

2024-11-21 09:42 UTC, psamusev commented on src/connectors/kadanza/readme.md
> +###Server
please add space before `Server` word - just formatting issue

2024-11-21 11:53 UTC, ivaylo-kostov-kad commented on src/connectors/kadanza/readme.md
> +###Server
Thanks!

2024-11-22 08:11 UTC, psamusev commented on src/connectors/kadanza/connector.ts
> +      case 'highres':
@ivaylo-kostov-kad  you can find supported formats under "Supported Formats" section https://docs.chiligrafx.com/GraFx-Developers/connectors/media-connector/media-connector-fundamentals/#download-method. In addition this PR can be used as a reference https://github.com/chili-publish/studio-sdk/pull/371

In short, we're working only with JPEG, PNG or PDF (In particular case) only

2024-11-22 14:34 UTC, ivaylo-kostov-kad commented on src/connectors/kadanza/connector.ts
> +      case 'highres':
@psamusev OK, thanks - that's clear. We don't expect GraFx to support other formats. Our expectation is that if an asset download is requested and the original is a non-supported format, loading (or rendering) the asset in the document will fail - that's fine for us. 
That's why you also see a TODO on line 197 - we will eventually decide whether we need to add custom logic for other formats when we actually start using the connector in real-life use-cases.

2024-11-26 11:58 UTC, psamusev commented on src/connectors/kadanza/connector.ts
> +      case 'highres':
@ivaylo-kostov-kad  this is exact behaviour of the Canvas - you won't see the asset if it's not recognised by the Engine that leads us to partially working connector behaviour. You would need to fix it as part of the PR to let us proceed with further testing and merge

2024-11-27 15:15 UTC, psamusev commented
@ivaylo-kostov-kad  May I ask you in addition update connector logo with this one 
![Kadanza_PrimarySymbol_rgb (1) (1)](https://github.com/user-attachments/assets/2646df96-71bc-400b-896c-0fb3cbd81917) - the logo should follow our style guide to be presented in a correct way later

2025-04-23 12:32 UTC, psamusev requested changes

2025-05-12 06:24 UTC, ivaylo-kostov-kad commented on src/connectors/kadanza/package.json
> +    "options": {"BASE_URL": null, "DEBUG": false},
Done.

2025-05-12 12:34 UTC, psamusev commented
@ivaylo-kostov-kad I'm gonna merge this for further testing on our Dev. In case of any new findings we will let you know
cc: @tbranko

2025-05-12 12:34 UTC, psamusev approved these changes

2025-05-12 12:35 UTC, merged