AEM connector
chili-publish/studio-connector-framework pull request #90
Opened 2024-12-20 14:38 UTC by michvh-dev

This is the basis of the aem connector 

Todo's:
- Add folder logic
- Update Readme

2024-12-23 10:18 UTC, psamusev commented on src/connectors/adobe-experience-manager/package.json
> +    "@adobe/jwt-auth": "^2.0.0",
do we need it?

2024-12-23 10:18 UTC, psamusev commented on package-lock.json
seems like should be removed

2024-12-23 10:18 UTC, psamusev commented on src/connectors/adobe-experience-manager/connector.ts
> +export enum AemRendition {
Can we define it as a string literal type, instead of enum?

2024-12-23 10:18 UTC, psamusev commented on src/connectors/adobe-experience-manager/connector.ts
> +    const root = (this.runtime.options['BASE_URL'] as string) || '';
Since it's a required runtime options, I propose to through an error instead

2024-12-23 10:18 UTC, psamusev commented on src/connectors/adobe-experience-manager/connector.ts
> +      } catch {}
In my opinion, worth to thrown specific error if something is wrong with formats

2024-12-23 10:18 UTC, psamusev commented on src/connectors/adobe-experience-manager/connector.ts
> +            `Contenthub DAM: Download failed ${result.status} - ${result.statusText}`
Seems like should be AEM in the error text

2024-12-23 10:18 UTC, psamusev commented on src/connectors/adobe-experience-manager/connector.ts
> +    return [
since you use `context.collection` in `query` it should be exposed here

2024-12-23 10:18 UTC, psamusev commented on src/connectors/adobe-experience-manager/connector.ts
> +        `Contenthub DAM: Query failed ${res.status} - ${res.statusText}`
`AEM` in error msg text

2024-12-23 10:18 UTC, psamusev commented on src/connectors/adobe-experience-manager/connector.ts
> +        `Contenthub DAM: Query failed ${res.status} - ${res.statusText}`
`AEM` in error msg text

2024-12-23 10:18 UTC, psamusev commented on src/connectors/adobe-experience-manager/package.json
> +  "description": "",
Please provide meaningful description

2024-12-23 10:18 UTC, psamusev commented on src/connectors/adobe-experience-manager/package.json
> +    "connectorName": "Adobe Experience manager",
```suggestion
    "connectorName": "Adobe Experience Manager",
```

2024-12-23 10:18 UTC, psamusev commented on src/connectors/adobe-experience-manager/readme.md
> +    --runtimeOption="renditionOverrides={\"thumbnail\": \"eam.customthumb.png\"}" \
Define them as options in `package.json` with default values. Otherwise they won't be exposed in Connector Management page for this connector

2024-12-23 10:23 UTC, michvh-dev commented on package-lock.json
is for creating test tokens in our test environment will remove

2024-12-23 10:27 UTC, michvh-dev commented on src/connectors/adobe-experience-manager/connector.ts
> +    return [
@psamusev waiting here on feedback of adobe how to support it, because now its not possible to search, filter it in collections

2024-12-23 10:36 UTC, michvh-dev commented on src/connectors/adobe-experience-manager/connector.ts
> +export enum AemRendition {
@psamusev i can change it, but seems not so bad to me to keep it as an enum so we can also check on the values, as now added here as validation of the runtime option

```   try {
        overrides = JSON.parse(renditionOverrides);

        const supportedRenditions = Object.values(AemRendition) as string[];
        // TODO ADD here check for KEYS
        const renditionKeysThatAreNotCorrect = Object.keys(overrides).filter(
          (key) => {
            return !supportedRenditions.includes(key);
          }
        );
        if (!renditionKeysThatAreNotCorrect) {
          throw new Error(
            `The renditionOverrides in the runtime options contains not supported renditions ${renditionKeysThatAreNotCorrect.join(
              ', '
            )}. The supported renditions are ${Object.values(AemRendition)}`
          );
        }
      } catch {
        throw new Error(
          'The renditionOverrides in the runtime options are not the correct format the expected format is JSON'
        );
      }```

2024-12-23 10:37 UTC, michvh-dev commented on src/connectors/adobe-experience-manager/connector.ts
> +export enum AemRendition {
Let me know if i need to change it @psamusev

2024-12-23 10:40 UTC, michvh-dev commented on src/connectors/adobe-experience-manager/readme.md
> +    --runtimeOption="renditionOverrides={\"thumbnail\": \"eam.customthumb.png\"}" \
Added this now as empty string `"renditionOverrides": ""`, because it uses the default aem ones, when filled in the default and custom ones are merged

2024-12-23 10:41 UTC, michvh-dev commented
@psamusev went through your comments, and updated the logic, i added one question about the enum

2024-12-23 11:26 UTC, michvh-dev commented on src/connectors/adobe-experience-manager/connector.ts
> +      },
@psamusev added here also the option, as in the Grafx Media connector to show folders in the connector as configuration option

2024-12-23 12:37 UTC, psamusev commented on src/connectors/adobe-experience-manager/connector.ts
> +      },
Do we really need it? Also please take into consideration that default state of connector configuration is `false` by default for boolean settings (until we introduce the `presets`)

2024-12-23 13:00 UTC, michvh-dev commented on src/connectors/adobe-experience-manager/connector.ts
> +      },
@psamusev it was default false when there was configuration added, so i would suggest to keep it, so the user has the possibility to enable the folders template variable level.

2025-01-03 11:46 UTC, psamusev commented on package-lock.json
Seems like file is till in place. Please remove it

2025-01-03 13:34 UTC, psamusev requested changes

2025-01-03 13:39 UTC, psamusev commented
During UI testing I've noticed that breadcrumbs within folder contains some extra items that were not presented as folders. Can we hide it( you don't need add them to `relativePath`) and use directly in the connector code, when build actual  request path?
Root level
<img width="314" alt="Screenshot 2025-01-03 at 16 34 07" src="https://github.com/user-attachments/assets/386111a5-e084-4be8-aec4-4ad5827a9733" />
Within "tccc" folder
<img width="285" alt="Screenshot 2025-01-03 at 16 34 15" src="https://github.com/user-attachments/assets/b9aa2e2f-aee8-4fd9-9886-7f503e2e9362" />

Expected to see "tccc" only in breadcrumbs

2025-01-04 08:23 UTC, michvh-dev commented
@psamusev this is now updated 

![Screenshot 2025-01-04 at 09 22 18](https://github.com/user-attachments/assets/839179f2-e318-4425-88b0-ea69ea877c6d)

2025-01-15 16:16 UTC, psamusev approved these changes

2025-01-15 16:21 UTC, seancrowe commented
Tested functionality - ready for testing on dev connector hub

2025-01-15 16:31 UTC, seancrowe approved these changes
Approved for merging

2025-01-15 16:37 UTC, merged